---
  - name: Create Pool and Pool Members
    hosts: extbigips intbigips
    connection: local
    tasks:

    - name: Create web external pool
      bigip_pool:
        state: present
        name: test1.cloudmegalodon.us_pool_http_80
        partition: Common
        lb_method: least-connections-member
        monitors:
          - https
        provider:
          "{{ provider }}"
      delegate_to: localhost
      with_dict:
        - "{{ intbigips }}"

    - name: Add pool member
      bigip_pool_member:
        state: present
        pool: splunk_sh-pool
        partition: Common
        host: 172.0.1.74
        port: 80
        priority_group: 9
        description: web_pool member
        provider:
          "{{ provider }}"
      delegate_to: localhost
      with_dict:
        - "{{ intbigips }}"
