---
  - name: big ip information
    hosts: mgmtbigips
    connection: local

    tasks:
      - name: License BIG-IP using a key
        bigip_device_license:
            provider: "{{ item.value.provider }}"
            license_key: "{{ item.value.license_key }}"
            accept_eula: yes
        delegate_to: localhost
        with_dict:
          - "{{ mgmtbigips }}"

      - name: Add VLAN Inspection Zone as untagged to interface 1.1
        bigip_vlan:
            state: present
            untagged_interface: 1.1
            name: "external"
            provider: "{{ item.value.provider }}"
        delegate_to: localhost
        with_dict:
          - "{{ mgmtbigips }}"

      - name: Add VLAN internal as tagged to interface 1.2
        bigip_vlan:
            state: present
            untagged_interface: 1.2
            name: "internal"
            provider: "{{ item.value.provider }}"
        delegate_to: localhost
        with_dict:
          - "{{ mgmtbigips }}"

      - name: Add VLAN SSLO Service Chain Out 1.3
        bigip_vlan:
            state: present
            untagged_interface: 1.3
            name: "sslo_out"
            provider: "{{ item.value.provider }}"
        delegate_to: localhost
        with_dict:
          - "{{ mgmtbigips }}"

      - name: Add VLAN SSLO Service Chain In 1.4
        bigip_vlan:
            state: present
            untagged_interface: 1.4
            name: "sslo_in"
            provider: "{{ item.value.provider }}"
        delegate_to: localhost
        with_dict:
          - "{{ mgmtbigips }}"

      - name: Create External Self IP
        bigip_selfip:
          address: "{{ item.value.external_selfip }}"
          name: externalSelfIP
          netmask: 255.255.255.128
          provider: "{{ item.value.provider }}"
          vlan: external
          state: present
        delegate_to: localhost
        with_dict:
          - "{{ mgmtbigips }}"

      - name: Create Internal Self IP
        bigip_selfip:
          address: "{{ item.value.internal_selfip }}"
          name: internalSelfIP
          netmask: 255.255.255.128
          provider: "{{ item.value.provider }}"
          vlan: internal
          state: present
          allow_service:
            - all
        delegate_to: localhost
        with_dict:
          - "{{ mgmtbigips }}"

      - name: Create SSLO Out Self IP
        bigip_selfip:
          address: "{{ item.value.sslo_out_selfip }}"
          name: ssloOutSelfIP
          netmask: 255.255.255.128
          provider: "{{ item.value.provider }}"
          vlan: sslo_out
          state: present
          allow_service:
            - all
        delegate_to: localhost
        with_dict:
          - "{{ mgmtbigips }}"

      - name: Create SSLO In Self IP
        bigip_selfip:
          address: "{{ item.value.sslo_in_selfip }}"
          name: ssloInSelfIP
          netmask: 255.255.255.128
          provider: "{{ item.value.provider }}"
          vlan: sslo_in
          state: present
          allow_service:
            - all
        delegate_to: localhost
        with_dict:
          - "{{ mgmtbigips }}"


      - name:  disable setup gui
        bigip_command:
          commands:
            - "modify sys global-settings gui-setup disabled"
          provider:
            "{{ item.value.provider }}"
        delegate_to: localhost
        with_dict:
          - "{{ mgmtbigips }}"
#tmsh save sys config

      - name: Resize Volume and save config
        bigip_command:
          commands:
            - "tmsh save sys config"
            - "modify sys disk directory /appdata new-size 50485760"
          provider:
            "{{ item.value.provider }}"
        delegate_to: localhost
        with_dict:
          - "{{ mgmtbigips }}"

      - name: Wait a maximum of 300 seconds for BIG-IP to be ready to take configuration
        bigip_wait:
          timeout: 300
          provider: "{{ item.value.provider }}"
        delegate_to: localhost
        with_dict:
          - "{{ mgmtbigips }}"

      - name: Set NTP server
        bigip_device_ntp:
          ntp_servers:
            - 192.0.2.23
          provider:
            "{{ item.value.provider }}"
        delegate_to: localhost
        with_dict:
          - "{{ mgmtbigips }}"
        tags:
          - time

      - name: Set timezone
        bigip_device_ntp:
          timezone: America/Los_Angeles
          provider:
            "{{ item.value.provider }}"
        delegate_to: localhost
        with_dict:
          - "{{ mgmtbigips }}"
        tags:
          - time
